# Generated by Django 3.1.3 on 2020-11-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalCompositon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chemical_compositon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChemicalElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'chemical_element',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommodityProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('inventory', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'commodity_properties',
                'managed': False,
            },
        ),
    ]
